live_config_reload = true

import = ["~/.config/alacritty/themes/deep_space.toml"]
[colors.bright]
black = "#b3b3b3"
# blue = "#465b80"
# cyan = "#385a73"
# green = "#3f6566"
# magenta = "#533969"
# red = "#735771"
# white = "#e5e5e5"
# yellow = "#807476"
#
[colors.cursor]
cursor = "#465b80"
text = "#e5e5e5"
#
[colors.normal]
black = "#0f1319"
# blue = "#3f5273"
# cyan = "#324f66"
# green = "#375759"
# magenta = "#543f66"
# red = "#644d66"
# white = "#b3b3b3"
# yellow = "#736871"
#
# [colors.primary]
# background = "#1f2329"
# foreground = "#b8bfe5"

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[selection]
save_to_clipboard = false

[window]
decorations_theme_variant = "None"
decorations = "none"
dynamic_title = true
opacity = 0.95

[scrolling]
multiplier = 3
history = 10000

[window.padding]
x = 5
y = 5
